spring:
  application:
    name: team-sudoku-api
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          format_sql: true
  flyway:
    enabled: true
    placeholders:
      '[admin.uid]': ${ADMIN_USER_FIREBASE_UID}
      '[admin.name]': "System Admin"
      '[admin.email]': "admin@example.com"


