# ./mvnw spring-boot:run -Dspring-boot.run.profiles=supabaseでこの設定ファイルを適用して実行
spring:
  datasource:
    url: jdbc:postgresql://${SUPABASE_DB_HOST}:5432/postgres?sslmode=require
    username: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate 

  flyway:
    enabled: true
    baseline-on-migrate: true